"""PlatformIO extra_script: gzip tools/webui/index.html into a PROGMEM
C header (firmware/pynt/rover/web_assets.h, gitignored — regenerated on
every build of an ENABLE_WEB_CONFIG env).

Wired via `extra_scripts = pre:tools/webui/build_assets.py` in the coex
env(s) and the web spike env. Envs that don't run it never include the
header (web_config.cpp is compiled out without ENABLE_WEB_CONFIG).
"""
import gzip
import os

Import("env")  # noqa: F821  (PlatformIO construct)

root = env["PROJECT_DIR"]
src = os.path.join(root, "tools", "webui", "index.html")
dst = os.path.join(root, "firmware", "pynt", "rover", "web_assets.h")

with open(src, "rb") as f:
    raw = f.read()
gz = gzip.compress(raw, 9, mtime=0)  # mtime=0 -> deterministic output

lines = []
lines.append("// AUTO-GENERATED by tools/webui/build_assets.py — do not edit.")
lines.append(f"// source: tools/webui/index.html ({len(raw)} B raw, {len(gz)} B gzipped)")
lines.append("#pragma once")
lines.append("#include <Arduino.h>")
lines.append(f"const size_t WEB_INDEX_GZ_LEN = {len(gz)};")
body = ", ".join(str(b) for b in gz)
lines.append(f"const uint8_t WEB_INDEX_GZ[] PROGMEM = {{{body}}};")
content = "\n".join(lines) + "\n"

# only rewrite when changed, so incremental builds stay incremental
old = None
if os.path.exists(dst):
    with open(dst) as f:
        old = f.read()
if old != content:
    with open(dst, "w") as f:
        f.write(content)
    print(f"[webui] web_assets.h regenerated ({len(raw)} B -> {len(gz)} B gz)")
