// Web config GUI (ENABLE_WEB_CONFIG, pynt-rover-coex only). W1 scope:
// GET / (gzipped SPA from PROGMEM) + GET /api/status (JSON snapshot),
// admin auth on by default, W2-W5 routes scaffolded as 501s.
//
// Concurrency model (docs/web-config-spike.md): the server is the
// LOWEST-priority superloop resident. Hand-rolled HTTP/1.1 state
// machine over WiFiServer/WiFiClient — one connection at a time,
// Connection: close, and at most ONE bounded read or write per loop
// pass so a slow phone can never stall the correction path. accept()
// (not available()) so browsers mid-handshake are picked up instantly.
//
// Auth: HTTP Basic, user "admin", password g_settings.adminPass —
// generated from the SAMD51 TRNG at first boot if unset (no hardcoded
// default), shown on the TFT WEB page, changeable via the W5 System
// card. The AP WPA2 password (W2) is generated the same way.
#include "web_config.h"

#include "features.h"

#if ENABLE_WEB_CONFIG

#include <WiFiNINA.h>

#include "gnss.h"
#include "ntrip.h"
#include "sd_logger.h"
#include "settings.h"
#include "shared.h"
#include "web_assets.h"  // generated by tools/webui/build_assets.py

namespace {

WiFiServer* server = nullptr;
bool serverUp = false;
WiFiClient conn;

enum class HttpState : uint8_t { Idle, ReadRequest, Respond };
HttpState state = HttpState::Idle;
uint32_t stateEnteredMs = 0;
constexpr uint32_t kRequestTimeoutMs = 2000;
constexpr uint32_t kResponseTimeoutMs = 8000;

// Request scratch: we only need the request line + Authorization header.
char reqLine[128];
size_t reqLen = 0;
bool reqLineDone = false;
char hdrLine[160];
size_t hdrLen = 0;
bool authOk = false;

// Response streaming (one bounded chunk per pass).
const uint8_t* rspBody = nullptr;  // PROGMEM or RAM
size_t rspBodyLen = 0, rspBodySent = 0;
char rspHead[224];
size_t rspHeadLen = 0, rspHeadSent = 0;
char jsonBuf[560];  // /api/status body lives here between passes
constexpr size_t kChunk = 1024;  // one TCP-buffer-sized write per pass

char expectedAuth[64];  // "Basic <b64(admin:pass)>" precomputed

bool apRequested = false;

// --- SAMD51 TRNG ------------------------------------------------------
uint32_t trng32() {
#ifdef __SAMD51__
  MCLK->APBCMASK.bit.TRNG_ = 1;
  TRNG->CTRLA.bit.ENABLE = 1;
  while (!TRNG->INTFLAG.bit.DATARDY) {}
  return TRNG->DATA.reg;
#else
  return micros() ^ (analogRead(A0) << 16);  // spike boards fallback
#endif
}

void genPassword(char* dst, size_t len) {
  // Unambiguous alphabet (no 0/O/1/l/I) — read off a 240x320 TFT.
  static const char tbl[] = "23456789abcdefghjkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ";
  for (size_t i = 0; i < len; i++) dst[i] = tbl[trng32() % (sizeof(tbl) - 1)];
  dst[len] = '\0';
}

void base64enc(const char* in, char* out, size_t outLen) {  // as ntrip.cpp
  static const char tbl[] =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  size_t n = strlen(in), o = 0;
  for (size_t i = 0; i < n && o + 4 < outLen; i += 3) {
    uint32_t v = (uint32_t)(uint8_t)in[i] << 16 |
                 (i + 1 < n ? (uint32_t)(uint8_t)in[i + 1] << 8 : 0) |
                 (i + 2 < n ? (uint32_t)(uint8_t)in[i + 2] : 0);
    out[o++] = tbl[(v >> 18) & 63];
    out[o++] = tbl[(v >> 12) & 63];
    out[o++] = (i + 1 < n) ? tbl[(v >> 6) & 63] : '=';
    out[o++] = (i + 2 < n) ? tbl[v & 63] : '=';
  }
  out[o] = '\0';
}

void computeExpectedAuth() {
  char creds[40];
  snprintf(creds, sizeof(creds), "admin:%s", g_settings.adminPass);
  char b64[56];
  base64enc(creds, b64, sizeof(b64));
  snprintf(expectedAuth, sizeof(expectedAuth), "Basic %s", b64);
}

// --- response builders ------------------------------------------------
void startResponse(const char* status, const char* type, const char* extra,
                   const uint8_t* body, size_t bodyLen) {
  rspHeadLen = (size_t)snprintf(
      rspHead, sizeof(rspHead),
      "HTTP/1.1 %s\r\nContent-Type: %s\r\nContent-Length: %u\r\n"
      "Cache-Control: no-store\r\nConnection: close\r\n%s\r\n",
      status, type, (unsigned)bodyLen, extra ? extra : "");
  rspHeadSent = 0;
  rspBody = body;
  rspBodyLen = bodyLen;
  rspBodySent = 0;
  state = HttpState::Respond;
  stateEnteredMs = millis();
}

void respond401() {
  static const char kBody[] = "{\"err\":\"auth\"}";
  startResponse("401 Unauthorized", "application/json",
                "WWW-Authenticate: Basic realm=\"pynt-rtk\"\r\n",
                (const uint8_t*)kBody, sizeof(kBody) - 1);
}

void respond404() {
  static const char kBody[] = "{\"err\":\"no such route\"}";
  startResponse("404 Not Found", "application/json", nullptr,
                (const uint8_t*)kBody, sizeof(kBody) - 1);
}

void respond501(const char* what) {
  int n = snprintf(jsonBuf, sizeof(jsonBuf),
                   "{\"err\":\"%s not implemented yet\"}", what);
  startResponse("501 Not Implemented", "application/json", nullptr,
                (const uint8_t*)jsonBuf, (size_t)(n > 0 ? n : 0));
}

void respondStatusJson() {
  uint32_t age = correctionAgeMs();
  long corrS = (age == UINT32_MAX) ? -1 : (long)(age / 1000);
  uint8_t ble = 0;
#if FEATURE_BLE
  ble = !g_link.bleUp        ? 0
        : g_link.bleSubscribed ? 3
        : g_link.bleConnected  ? 2
                               : 1;
#endif
  const char* fn = g_log.fileName[0]
                       ? (strrchr(g_log.fileName, '/')
                              ? strrchr(g_log.fileName, '/') + 1
                              : g_log.fileName)
                       : "";
  int n = snprintf(
      jsonBuf, sizeof(jsonBuf),
      "{\"fix\":%u,\"carr\":%u,\"sv\":%u,\"lat\":%.7f,\"lon\":%.7f,"
      "\"alt\":%.1f,\"hacc\":%lu,\"pdop\":%.1f,\"ntrip\":\"%s\","
      "\"corr\":%ld,\"rssi\":%d,\"ip\":\"%s\",\"tcp\":%u,\"ble\":%u,"
      "\"sd\":%d,\"file\":\"%s\",\"kb\":%lu,\"freemb\":%lu,"
      "\"up\":%lu,\"mode\":\"%s\"}",
      g_gnss.fixType, g_gnss.carrSoln, g_gnss.numSV, g_gnss.latDeg,
      g_gnss.lonDeg, g_gnss.hMslM, (unsigned long)g_gnss.hAccMm,
      g_gnss.pdop, ntripStateName(), corrS, g_link.wifiRssi,
      g_link.wifiIp, g_link.tcpClients, ble, g_log.sdOk ? 1 : 0, fn,
      (unsigned long)(g_log.bytesWritten / 1024),
      (unsigned long)(g_log.sdFreeKB / 1024), (unsigned long)(millis() / 1000),
      g_settings.mode == DeviceMode::Base ? "base" : "rover");
  startResponse("200 OK", "application/json", nullptr,
                (const uint8_t*)jsonBuf, (size_t)(n > 0 ? n : 0));
}

// --- routing ----------------------------------------------------------
void route() {
  // reqLine: "GET /path HTTP/1.1"
  char* path = strchr(reqLine, ' ');
  if (!path) { respond404(); return; }
  *path++ = '\0';
  char* end = strchr(path, ' ');
  if (end) *end = '\0';
  const bool isGet = !strcmp(reqLine, "GET");

  if (!authOk) { respond401(); return; }

  if (isGet && (!strcmp(path, "/") || !strcmp(path, "/index.html"))) {
    startResponse("200 OK", "text/html; charset=utf-8",
                  "Content-Encoding: gzip\r\n", WEB_INDEX_GZ,
                  WEB_INDEX_GZ_LEN);
    return;
  }
  if (isGet && !strcmp(path, "/api/status")) { respondStatusJson(); return; }

  // W2-W5 scaffolding — structure visible, bodies land per-increment.
  // W2 (AP provisioning flow) is BLOCKED on the W0 beginAP+BLE spike.
  if (!strncmp(path, "/api/wifi", 9))     { respond501("wifi (W2)"); return; }
  if (!strncmp(path, "/api/scan", 9))     { respond501("scan (W2)"); return; }
  if (!strncmp(path, "/api/gnss", 9))     { respond501("gnss (W3)"); return; }
  if (!strncmp(path, "/api/ntrip", 10))   { respond501("ntrip (W3)"); return; }
  if (!strncmp(path, "/api/ble", 8))      { respond501("ble (W5)"); return; }
  if (!strncmp(path, "/api/log", 8))      { respond501("logging (W4)"); return; }
  if (!strncmp(path, "/api/system", 11))  { respond501("system (W5)"); return; }

  respond404();
}

// --- state machine ----------------------------------------------------
void resetConn() {
  conn.stop();
  conn = WiFiClient();
  state = HttpState::Idle;
  reqLen = hdrLen = 0;
  reqLineDone = false;
  authOk = false;
}

void pollIdle() {
  if (!server) return;
  WiFiClient incoming = server->accept();
  if (!incoming) return;
  conn = incoming;
  state = HttpState::ReadRequest;
  stateEnteredMs = millis();
  reqLen = hdrLen = 0;
  reqLineDone = false;
  authOk = false;
}

void pollRead() {
  if (!conn.connected() || millis() - stateEnteredMs > kRequestTimeoutMs) {
    resetConn();
    return;
  }
  // Bounded: drain what's buffered this pass, stop at end of headers.
  int budget = 512;
  while (budget-- > 0 && conn.available()) {
    char c = (char)conn.read();
    if (!reqLineDone) {
      if (c == '\n') {
        reqLine[reqLen] = '\0';
        reqLineDone = true;
      } else if (c != '\r' && reqLen < sizeof(reqLine) - 1) {
        reqLine[reqLen++] = c;
      }
      continue;
    }
    if (c == '\n') {
      hdrLine[hdrLen] = '\0';
      if (hdrLen == 0) { route(); return; }  // blank line = headers done
      if (!strncasecmp(hdrLine, "Authorization:", 14)) {
        const char* v = hdrLine + 14;
        while (*v == ' ') v++;
        if (!strcmp(v, expectedAuth)) authOk = true;
      }
      hdrLen = 0;
    } else if (c != '\r' && hdrLen < sizeof(hdrLine) - 1) {
      hdrLine[hdrLen++] = c;
    }
  }
}

void pollRespond() {
  if (!conn.connected() || millis() - stateEnteredMs > kResponseTimeoutMs) {
    resetConn();
    return;
  }
  // One bounded write per pass: headers first, then body chunks.
  if (rspHeadSent < rspHeadLen) {
    rspHeadSent += conn.write((const uint8_t*)rspHead + rspHeadSent,
                              rspHeadLen - rspHeadSent);
    return;
  }
  if (rspBodySent < rspBodyLen) {
    size_t n = rspBodyLen - rspBodySent;
    if (n > kChunk) n = kChunk;
    rspBodySent += conn.write(rspBody + rspBodySent, n);
    return;
  }
  resetConn();  // Connection: close
}

}  // namespace

void webConfigInit() {
  if (!g_settings.webEnable) {
    Serial.println(F("[web] disabled (webenable=0)"));
    return;
  }
  bool dirty = false;
  if (!g_settings.adminPass[0]) {
    genPassword(g_settings.adminPass, 10);
    Serial.println(F("[web] generated admin password (TFT WEB page shows it)"));
    dirty = true;
  }
  if (!g_settings.apPass[0]) {
    genPassword(g_settings.apPass, 10);
    dirty = true;
  }
  if (dirty) settingsSave();
  computeExpectedAuth();

  WiFi.setHostname(g_settings.hostname);  // takes effect on next join;
                                          // W0 spike verifies support

  static WiFiServer srv(g_settings.webPort);
  server = &srv;
  // Bind happens lazily once WiFi is up (same lesson as tcp_nmea).
  Serial.print(F("[web] config GUI on :"));
  Serial.println(g_settings.webPort);
}

void webConfigPoll() {
  if (!g_settings.webEnable || !server) return;

  if (WiFi.status() != WL_CONNECTED) {
    if (serverUp) { serverUp = false; resetConn(); }
    return;  // W2 adds the AP-mode path here
  }
  if (!serverUp) {
    server->begin();
    serverUp = true;
  }

  switch (state) {
    case HttpState::Idle:        pollIdle(); break;
    case HttpState::ReadRequest: pollRead(); break;
    case HttpState::Respond:     pollRespond(); break;
  }
}

void webConfigRequestApMode() {
  apRequested = !apRequested;
  // W2: actual beginAP() switch lands after the W0 spike answers whether
  // AP mode coexists with BLE HCI (or needs bleNus paused) on nina-fw
  // 3.0.1. Until then the button just arms/disarms the request flag.
  Serial.println(apRequested
                     ? F("[web] AP mode requested — W2 not implemented yet "
                         "(blocked on W0 beginAP+BLE spike)")
                     : F("[web] AP mode request cleared"));
}

bool webConfigApRequested() { return apRequested; }
const char* webConfigAdminPass() { return g_settings.adminPass; }
const char* webConfigApPass() { return g_settings.apPass; }

#endif  // ENABLE_WEB_CONFIG
